name = "nextjs-boilerplate"
compatibility_date = "2025-11-08"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @opennextjs/cloudflare"

[pages]
build_output_dir = ".vercel/output/static"
